spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
          temperature: 0.7
ai:
  openai:
    chat:
      model: gpt-4
      temperature: 0.7
    embedding:
      model: text-embedding-3-small
db:
  chroma:
    url: http://localhost:8000
    collection: dhamma_talks
    cleanDataDelay: 3600000